language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:xorg-edgers/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cmake 'libxcb.*-dev' xcb-proto python-xcbgen

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - mkdir build
  - cd build

script:
  - cmake ..
  - make
  - ctest --output-on-failure

env:
  - CXXFLAGS=
  - CXXFLAGS=-std=c++0x
