language: python

python:
  - "3.3"

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cmake 'libxcb.*-dev'

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - mkdir build
  - cd build

script:
  - cmake ..
  - make -j5
  - ctest --output-on-failure
